// Generated by CoffeeScript 1.6.1
(function() {
  var circle, get_hour_rgb, get_mid_rgb, hsv_to_rgb, mid_point, style_from_rgb,
    _this = this;

  circle = function(context, x, y, radius) {
    return context.arc(x, y, radius, 0, 2 * Math.PI, false);
  };

  hsv_to_rgb = function(h, s, v) {
    var b, f, g, i, p, q, r, t;
    h = h % 1;
    if (h < 0) {
      h += 1;
    }
    i = Math.floor(h * 6);
    f = h * 6 - i;
    p = v * (1 - s);
    q = v * (1 - f * s);
    t = v * (1 - (1 - f) * s);
    switch (i % 6) {
      case 0:
        r = v;
        g = t;
        b = p;
        break;
      case 1:
        r = q;
        g = v;
        b = p;
        break;
      case 2:
        r = p;
        g = v;
        b = t;
        break;
      case 3:
        r = p;
        g = q;
        b = v;
        break;
      case 4:
        r = t;
        g = p;
        b = v;
        break;
      case 5:
        r = v;
        g = p;
        b = q;
    }
    return [r, g, b];
  };

  get_hour_rgb = function(hour) {
    var h, i, s, v;
    i = hour;
    h = (i % 24) / 24;
    s = v = 1;
    return hsv_to_rgb(h, s, v);
  };

  mid_point = function(x, y, r) {
    return x * (1 - r) + y * r;
  };

  get_mid_rgb = function(rgb1, rgb2, r) {
    var i, _i, _len, _ref, _results;
    _ref = [0, 1, 2];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _results.push(rgb1[i] * (1 - r) + rgb2[i] * r);
    }
    return _results;
  };

  style_from_rgb = function(rgb) {
    var f;
    f = Math.floor;
    return "rgb(" + (f(255 * rgb[0])) + "," + (f(255 * rgb[1])) + "," + (f(255 * rgb[2])) + ")";
  };

  jQuery(function($) {
    var bg_canvas, bg_hour, bg_minute, bheight, bwidth, canvas, col_count, drawClock, height, margin, redrawBgCanvas, row_count, width;
    canvas = $('#clock').get(0);
    width = canvas.width = $(document).width();
    height = canvas.height = $(document).height();
    row_count = 6;
    col_count = 8;
    margin = height / (row_count + 1) / (row_count + 3);
    bheight = height / (row_count + 1);
    bwidth = (width - margin * (col_count + 3)) / col_count;
    bg_hour = bg_minute = null;
    bg_canvas = $("<canvas></canvas>").attr({
      width: width,
      height: height
    }).get(0);
    redrawBgCanvas = function() {
      var col, context, hour, i, minute, now, row, _i, _results;
      context = bg_canvas.getContext('2d');
      now = new Date;
      hour = now.getHours();
      minute = now.getMinutes();
      now = new Date;
      context.fillStyle = style_from_rgb(get_mid_rgb(get_hour_rgb(hour), get_hour_rgb((hour + 1) % 24), minute / 60));
      context.fillRect(0, 0, width, height);
      _results = [];
      for (i = _i = 0; _i < 24; i = ++_i) {
        if ((0 <= i && i < col_count)) {
          row = 0;
          col = i;
        } else if ((col_count <= i && i < 12)) {
          row = i - col_count + 1;
          col = col_count - 1;
        } else if ((12 <= i && i < 12 + col_count)) {
          row = row_count - 1;
          col = (col_count - 1) - (i - 12);
        } else {
          row = 24 - i;
          col = 0;
        }
        context.fillStyle = style_from_rgb(get_hour_rgb(i % 24));
        _results.push(context.fillRect(col * bwidth + (col + 2) * margin, row * bheight + (row + 2) * margin, bwidth, bheight));
      }
      return _results;
    };
    drawClock = function() {
      var context, curr, dx, dy, hour, minute, next, now, prev, s, seconds, x, y, _ref;
      context = canvas.getContext('2d');
      now = new Date;
      hour = now.getHours();
      minute = now.getMinutes();
      seconds = now.getSeconds() + now.getMilliseconds() / 1000;
      if ([hour, minute] !== [bg_hour, bg_minute]) {
        _ref = [hour, minute], bg_hour = _ref[0], bg_minute = _ref[1];
        redrawBgCanvas();
      }
      context.drawImage(bg_canvas, 0, 0);
      curr = seconds / 2.5;
      prev = Math.floor(curr);
      next = Math.ceil(curr);
      context.fillStyle = style_from_rgb(get_mid_rgb(get_hour_rgb(prev), get_hour_rgb(next), curr - prev));
      s = (seconds % 30) / 2.5;
      if ((0 <= s && s <= 1)) {
        dx = 0;
        dy = 0;
      } else if ((1 <= s && s <= 6)) {
        dx = (s - 1) / 5;
        dy = 0;
      } else if ((6 <= s && s <= 8)) {
        dx = 1;
        dy = 0;
      } else if ((8 <= s && s <= 11)) {
        dx = 1;
        dy = (s - 8) / 3;
      } else {
        dx = dy = 1;
      }
      if (seconds > 30) {
        dx = 1 - dx;
        dy = 1 - dy;
      }
      x = margin * 2 + (bwidth + margin) * mid_point(1, col_count - 2, dx);
      y = margin * 2 + (bheight + margin) * mid_point(1, row_count - 2, dy);
      return context.fillRect(x, y, bwidth, bheight);
    };
    return setInterval(drawClock, 50);
  });

}).call(this);
